# SwiftLint Configuration for SwiftFSRS
# Strict ruleset for maximum code quality

# Paths to include/exclude
included:
  - Sources
  - Tests

excluded:
  - .build
  - .swiftpm
  - Packages
  - DerivedData
  - "**/Package.swift"

# Analyzer rules require building the project
analyzer_rules:
  - unused_declaration
  - unused_import

# Enabled opt-in rules for strict checking
opt_in_rules:
  # Closure rules
  - closure_end_indentation
  - closure_spacing
  - trailing_closure
  
  # Documentation
  - missing_docs
  
  # Syntax
  - explicit_init
  - extension_access_modifier
  - file_header
  - implicit_return
  - multiline_arguments
  - multiline_function_chains
  - multiline_literal_brackets
  - multiline_parameters
  - multiline_parameters_brackets
  
  # Best practices
  - operator_usage_whitespace
  - overridden_super_call
  - private_action
  - private_outlet
  - prohibited_super_call
  - redundant_nil_coalescing
  - redundant_type_annotation
  - toggle_bool
  - unneeded_parentheses_in_closure_argument
  - vertical_whitespace_closing_braces
  - vertical_whitespace_opening_braces
  - yoda_condition
  
  # Naming
  - pattern_matching_keywords
  - prefixed_toplevel_constant
  
  # Collections
  - contains_over_filter_count
  - contains_over_filter_is_empty
  - contains_over_first_not_nil
  - contains_over_range_nil_comparison
  - empty_collection_literal
  - empty_count
  - empty_string
  - first_where
  - last_where
  - reduce_into
  - sorted_first_last
  
  # Control flow
  - fatal_error_message
  - flatmap_over_map_reduce
  - force_unwrapping
  - implicitly_unwrapped_optional
  - joined_default_parameter
  - optional_enum_case_matching
  
  # Performance
  - reduce_boolean
  
  # Attributes
  - attributes
  - modifier_order
  
  # Miscellaneous
  - convenience_type
  - discouraged_object_literal
  - discouraged_optional_boolean
  - discouraged_optional_collection
  - fallthrough
  - file_name
  - file_name_no_space
  - literal_expression_end_indentation
  - lower_acl_than_parent
  - number_separator
  - object_literal
  - static_operator
  - strong_iboutlet
  - switch_case_on_newline
  - test_case_accessibility
  - unavailable_function
  - unowned_variable_capture
  - vertical_parameter_alignment_on_call

# Disabled rules (conflicts or too strict for this codebase)
disabled_rules:
  - todo
  - function_body_length
  - file_length
  - function_default_parameter_at_end
  - type_body_length
  - cyclomatic_complexity
  - nesting
  - identifier_name

# Rule configurations
line_length:
  warning: 120
  error: 150
  ignores_urls: true
  ignores_function_declarations: true
  ignores_comments: true

type_name:
  min_length: 3
  max_length:
    warning: 45
    error: 55
  excluded:
    - T
    - U
    - V

large_tuple:
  warning: 3
  error: 4

function_parameter_count:
  warning: 6
  error: 8

# Documentation requirements
missing_docs:
  warning: public
  excludes_extensions: true
  excludes_inherited_types: true

# Trailing whitespace
trailing_whitespace:
  ignores_empty_lines: true
  ignores_comments: false

# Vertical whitespace
vertical_whitespace:
  max_empty_lines: 2

# Force unwrapping - strict but allow in tests
force_unwrapping:
  severity: error

# Force cast - avoid in production code
force_cast:
  severity: error

# Force try - avoid, use proper error handling
force_try:
  severity: error

# Implicitly unwrapped optionals - minimize usage
implicitly_unwrapped_optional:
  mode: all_except_iboutlets
  severity: warning

# Control statement - require braces
control_statement:
  severity: error

# Colon spacing
colon:
  flexible_right_spacing: false
  apply_to_dictionaries: true

# Comma spacing
comma:
  severity: error

# Opening brace spacing
opening_brace:
  severity: error

# Return arrow whitespace
return_arrow_whitespace:
  severity: error

# Operator whitespace
function_name_whitespace:
  severity: error

# Statement position (else, catch on same line)
statement_position:
  statement_mode: default
  severity: error

# Trailing comma in arrays/dictionaries
trailing_comma:
  mandatory_comma: true

# Void return
void_return:
  severity: error

# Redundant optional initialization
implicit_optional_initialization:
  severity: warning

# Redundant discardable let
redundant_discardable_let:
  severity: warning

# Syntactic sugar for types
syntactic_sugar:
  severity: error

# Legacy constructor
legacy_constructor:
  severity: error

# Legacy constant
legacy_constant:
  severity: error

# Unused closure parameter
unused_closure_parameter:
  severity: warning

# Unused enumerated
unused_enumerated:
  severity: warning

# Unused optional binding
unused_optional_binding:
  severity: warning

# Custom rules
custom_rules:
  # Prefer weak self in escaping closures
  weak_self_in_closures:
    name: "Weak Self in Closures"
    regex: '(?<!weak )\bself\.'
    match_kinds:
      - identifier
    message: "Consider using [weak self] in escaping closures to avoid retain cycles"
    severity: warning
  
  # Avoid print statements (use logger instead)
  no_print:
    name: "No Print Statements"
    regex: '\bprint\('
    message: "Use the logger instead of print statements"
    severity: warning
    
  # Prefer explicit self in closures
  explicit_self_in_closures:
    name: "Explicit Self in Closures"
    regex: '\[weak self\].*\n.*(?<!self\.)\w+\s*='
    message: "Use explicit self when using [weak self]"
    severity: warning

# Reporter type (xcode, json, csv, checkstyle, junit, html, emoji, sonarqube, markdown, github-actions-logging)
reporter: "xcode"

